https://www.tensorflow.org/ 

![TensorFlow](images/tensorflow.png)

# Learning TensorFlow





## Install 

Install using conda in linux
```bash
conda create -n tensorflow python=3.5
source activate tensorflow
conda install pandas matplotlib jupyter notebook scipy scikit-learn
pip install tensorflow
```

## Activate/Deactivate python env


```bash
source activate tensorflow
deactivate tensorflow
```

## Write the first program 

In [5]:
from tensorflow.examples.tutorials.mnist import input_data
import numpy as np
# Download the mnist dataset. 
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [7]:
import tensorflow as tf
import numpy as np
helloworld = tf.constant("Hello World !") # Objects created by TF is call tensor
output = tf.Session().run(helloworld)     # Run the constant in the TF session
print(output)

b'Hello World !'


---
# Tensor

A mathematical object analogous to but more general than a vector, represented by an array of components that are functions of the coordinates of a space. **The central unit of data in TensorFlow is the tensor**. Everything store in TF as a tensor object.

- **Rank 0 Tensor**:

    + Scaler is a rank 0 tensor and in TF it represent as follows.

    + *This is a constant tensor that does not change*

    ```js
    A = tf.constant(123)
    ``` 



- **Rank 1 Tensor**:

    + Rank 1 Tensor is a Vector and in TF it represents as follows 

    ```js
    B = ft.constant([23, 49, 42])
    ```

- **Rank 2 Tensor**:

    + Rank 2 Tensor is a Matrix and in TF it represent as follows

    ```js
    C = ft.constant([[23,21,89], [34,982,83]])
    ```

- **Rank 3 Tensor**:

    + Rank 3 Tensor is a 3D array and in TF it represent as follows

    ```js
    D = ft.constant([[[1., 2., 3.]], [[7., 8., 9.]]])
    ```


---
# Session

TF api is build around the idea of building a computational grpah of notes and running them. A session encapsulates the control and state of the TensorFlow runtime. 


## Work with constant tensors

In [10]:
node1 = tf.constant(3.0, dtype=tf.float32)
node2 = tf.constant(4.0) 
print(node1)

Tensor("Const_5:0", shape=(), dtype=float32)


### Add two tensors
Adding two tensors (nodes) produce This will procuce a another tensor (node). 

![](images/tf.add.run.jpeg)

In [20]:
node3 = tf.add(node1, node2)
sess = tf.Session()
numerical_output = sess.run(node3)
print(numerical_output)

7.0


### Placeholders In TenforFlow 

In [26]:
x = tf.placeholder(tf.float32)  # x is a Tensor variable that takes integer value
y = tf.placeholder(tf.float32)  # y is a Tensor variable that takes integer value
sum_xy = x + y # this is same as tf.add(x, y)
sess.run(sum_xy, feed_dict={x:13, y:2})

15.0

In [27]:
sess.run(sum_xy, feed_dict={x:2, y:2})

4.0

### Variables in TensorFlow 

- TF variables can be modify as usual variables.
- Regular variables does not get initialize when creating them
- Call *global_variables_initializer()* method and run that within the session.

In [28]:
x = tf.Variable(5) # x is initialize with 5 and can be modify
init = tf.global_variables_initializer()
sess.run(init)
sess.run(x)

5

# TensorFlow Math 

In [29]:
a = tf.add(5, 2)  # 7

In [30]:
b = tf.subtract(10, 4) # 6

In [31]:
c = tf.multiply(2, 5)

In [32]:
print(sess.run([a, b, c]))

[7, 6, 10]


# Type Casting in TF

Type cast float to integer

In [35]:
x = tf.constant(2.0) # Floating point number 
print(sess.run(x))

2.0


In [36]:
y = tf.cast(x, tf.int32) # Integer number
print(sess.run(y))

2


# Define Linear Function 

$y=xW + b$

![](images/linearfunction.jpg)

## Define the input variable $x$


$x_i$ is an input. For example this can be a vector of an image. So lets assume this is a vector length of 5

![](images/x_matrix.jpg)

In [37]:
number_of_data_vectors = 120 # this could be the number of images I have in my data set
length_of_data_vector = 6 # length of the ibserved data vector
number_of_categories = 5 # this is the number of categories I have to categorize

_Note: Randomly generating $x_i$ vectors just for the demonstration. In real project these are the observed data (ex, image with (20px) x (20px) = (300px))_

In [39]:
x = tf.Variable(tf.truncated_normal((number_of_data_vectors, length_of_data_vector)))
sess.run(tf.global_variables_initializer()) # Initialize the variable x in the session (sess)
sess.run(x)[:10] # Print the first 10 

array([[-1.37163258, -1.120718  ,  0.68117326,  0.23860668,  0.24659702,
        -0.26429233],
       [-0.48678681,  0.3188653 , -0.340094  ,  1.33552933, -1.20779932,
         0.10314474],
       [ 0.81822699,  0.237031  , -1.21460426,  0.19686605,  1.65755033,
        -1.4732542 ],
       [-0.89723796,  0.41721019,  0.8114472 , -1.45597553, -0.20714021,
         0.87003368],
       [-0.35346675, -0.19916253, -0.00629265, -0.44648668, -0.47050682,
        -0.58709157],
       [ 0.03624677,  0.88690758,  0.35367313,  0.02107221, -0.15830362,
        -1.30137086],
       [-0.18690935,  0.68616128,  0.62040877, -1.09216321, -0.77091652,
         1.03800392],
       [ 0.82689762, -1.2707144 ,  0.80740076, -0.07831069, -1.87000883,
         1.40973043],
       [ 0.46644118,  0.66127664,  0.71061063, -0.08717158, -0.11512861,
        -0.33586648],
       [ 1.12521851, -0.2940726 ,  1.92749083, -0.32153317,  0.74235499,
         0.02747563]], dtype=float32)

## Define weights $W$

Initializing the weights with random values is important. Randomizing weights help the model get stuck in local minima everytime we train it. Choosing random weights from a normal distribution is a good practice. 


![](images/w_matrix.jpg)

In [40]:
W = tf.Variable(tf.truncated_normal((length_of_data_vector, number_of_categories)))
sess.run(tf.global_variables_initializer())
sess.run(W)

array([[ 0.56659377,  0.52709264, -0.37136295, -0.78344363,  0.17407295],
       [ 0.94869137, -1.07415283,  1.47083795,  0.03947164, -0.36679548],
       [-1.81448364, -0.88770545, -1.11148608, -0.9016487 , -1.53345048],
       [ 0.3157762 , -1.13129508,  0.15810594,  0.05171677,  0.25179809],
       [ 0.78519398,  0.08177385,  0.57111883, -1.43667269, -0.50185204],
       [ 1.245767  , -0.23355483, -0.50478655, -0.17875008, -0.55706263]], dtype=float32)

## Define biases $b$

Biases also can be initialize with random values. Since weights are initialize with random values, we can define biases with zero.

![](images/b.jpg)

In [41]:
b = tf.Variable(tf.zeros(number_of_categories))

In [42]:
sess.run(tf.global_variables_initializer()) 
sess.run(b)

array([ 0.,  0.,  0.,  0.,  0.], dtype=float32)

## Calculate the linear function   
$y=xW + b$

![](images/linear.jpg)

In [43]:
y = tf.add(tf.matmul(x, W), b)
sess.run(y)[:10]

array([[  1.92972851e+00,  -5.25490999e-01,   2.28202254e-01,
          2.15020239e-01,   1.90408409e+00],
       [ -1.32976270e+00,  -9.11482036e-01,  -5.06391108e-01,
         -1.44871545e+00,   2.21602416e+00],
       [ -2.17019990e-01,  -4.21251655e-02,   1.22052431e-03,
         -8.92342985e-01,   2.54472399e+00],
       [  2.27298355e+00,   6.38400912e-01,   8.35950315e-01,
         -6.33156896e-02,  -3.95241499e-01],
       [ -2.06318930e-01,   1.61427116e+00,   5.17454576e+00,
         -2.72287250e-01,   1.57459676e-02],
       [  7.60614336e-01,   8.81396890e-01,   2.27614260e+00,
          4.87145245e-01,  -4.02337611e-01],
       [  6.79154038e-01,  -7.69664347e-01,  -1.25312769e+00,
          1.95053554e+00,  -1.99529970e+00],
       [  1.67160082e+00,  -2.56617069e+00,  -2.56597471e+00,
         -2.37421393e-01,   3.56479359e+00],
       [  7.65899777e-01,   4.60203111e-01,   1.76322770e+00,
          2.57929039e+00,  -3.22916174e+00],
       [ -1.64316690e+00,  -1.6809904

# Calculate the softmax

Softmax function scale $y$ to be between $0$ and $1$

![](images/softmax.jpg)

![](images/softmaxy.jpg)

In [44]:
y = tf.nn.softmax(y)    
sess.run(y)[:10]

array([[ 0.41272056,  0.03542973,  0.07528225,  0.07429639,  0.40227115],
       [ 0.02478172,  0.03765203,  0.05645693,  0.02200245,  0.85910684],
       [ 0.05057805,  0.06024458,  0.06291334,  0.02574382,  0.80052018],
       [ 0.62549824,  0.12199327,  0.14863822,  0.06047617,  0.0433941 ],
       [ 0.00441364,  0.02725644,  0.95868689,  0.00413188,  0.0055111 ],
       [ 0.12897398,  0.14553158,  0.58706695,  0.09811512,  0.04031239],
       [ 0.19942625,  0.04683479,  0.02888039,  0.71110922,  0.01374934],
       [ 0.12791578,  0.00184707,  0.00184743,  0.01896035,  0.84942943],
       [ 0.09436414,  0.06950958,  0.25582385,  0.57856554,  0.0017369 ],
       [ 0.05090566,  0.04901619,  0.02895823,  0.1008275 ,  0.77029246]], dtype=float32)

# Clculate Cross Entropy in TensorFlow

In [45]:
# start from here 
y_hat_data = mnist.test.labels.astype(np.float32) # just to simulate, I am loading lables from mist dataset
y_hat_data = y_hat_data[:,[1, 2, 3, 4, 5]][:120]
print(y_hat_data[:10]) # show the first 10 rows 
y_hat = tf.Variable(y_hat_data)
sess.run(tf.global_variables_initializer())
print(y_hat)

[[ 0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]]
<tf.Variable 'Variable_5:0' shape=(120, 5) dtype=float32_ref>


![](images/crossentropydata.jpg)

In [46]:
crosse = -tf.reduce_sum(tf.multiply(tf.log(y), y_hat))

# Mini Batching 

It takes so much memory to train a model with large dataset. This may be not be realaistic even with less expensive memory. As a solution, we can use the mini batching: take subsets of data from the whole dataset and train the model for each subset. This is not ideal but its allows us to train the model with less amount of memory.

In [47]:
n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# Import MNIST data
# mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

# The features are already scaled and the data is shuffled
train_features = mnist.train.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))

## Divide the data in to batches

## Create the model


![](images/graph1.jpg)

In [48]:
learning_rate = 0.001
n_input = 784  # MNIST data input (img shape: 28*28)
n_classes = 10  # MNIST total classes (0-9 digits)

# The features are already scaled and the data is shuffled
train_features = mnist.train.images
test_features = mnist.test.images

train_labels = mnist.train.labels.astype(np.float32)
test_labels = mnist.test.labels.astype(np.float32)

# Features and Labels
features = tf.placeholder(tf.float32, [None, n_input])
labels = tf.placeholder(tf.float32, [None, n_classes])

# Weights & bias
weights = tf.Variable(tf.random_normal([n_input, n_classes]))
bias = tf.Variable(tf.random_normal([n_classes]))
 
# Logits - xW + b
logits = tf.add(tf.matmul(features, weights), bias)

# Define loss and optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=labels))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(cost)

# Calculate accuracy
correct_prediction = tf.equal(tf.argmax(logits, 1), tf.argmax(labels, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))


# TODO: Set batch size
batch_size = 128
assert batch_size is not None, 'You must set the batch size'

# Train the model using entier dataset

In [49]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    # Use the enter dataset
    sess.run(optimizer, feed_dict={features: train_features, labels: train_labels})
    test_accuracy = sess.run(
        accuracy,
        feed_dict={features: test_features, labels: test_labels})

print('Test Accuracy: {}'.format(test_accuracy))


Test Accuracy: 0.04450000077486038


# Train the model using Mini-batches

## Create batches
![](images/batch.jpg)

In [153]:
import math
def batches(batch_size, features, labels):
    """
    Create batches of features and labels
    :param batch_size: The batch size
    :param features: List of features
    :param labels: List of labels
    :return: Batches of (Features, Labels)
    """
    assert len(features) == len(labels)
    outout_batches = []
    
    sample_size = len(features)
    for start_i in range(0, sample_size, batch_size):
        end_i = start_i + batch_size
        batch = [features[start_i:end_i], labels[start_i:end_i]]
        outout_batches.append(batch)
        
    return outout_batches


## Train 

In [152]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)    
    # Train the optimizer for each batch
    for batch_features, batch_labels in batches(batch_size, train_features, train_labels):
        sess.run(optimizer, feed_dict={features: batch_features, labels: batch_labels})

    # Calculate accuracy for test dataset
    test_accuracy = sess.run(
        accuracy,
        feed_dict={features: test_features, labels: test_labels})

print('Test Accuracy: {}'.format(test_accuracy))


Test Accuracy: 0.06440000236034393


# Epochs

- Epoch is a single training (forward and backward pass) of the entier dataset. If we are using mini-batches, we have to train with all the batches within a epoch. 
- This increase the accuracy of th model without requiring more data. 

![](images/epochs.jpg)